version: "3.3"

services:
  # postgres:
  #   restart: always
  #   image: postgres:15-alpine
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #   <<: *environment

  formbricks:
    restart: always
    image: ghcr.io/formbricks/formbricks:latest
    # depends_on:
    #   - postgres
    ports:
      - 9090:3000
    volumes:
      - uploads:/apps/web/uploads/
    environment: # https://formbricks.com/docs/self-hosting/docker#important-run-time-variables
      # The url of your Formbricks instance used in the admin panel
      WEBAPP_URL: https://survey.proximabiz.net

      # PostgreSQL DB for Formbricks to connect to
      # DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/formbricks?schema=public"
      DATABASE_URL: "postgresql://postgres:DDxlOdlzt4NXvtsrMUE500@linkup.cxn6melzh32j.ap-south-1.rds.amazonaws.com:5432/formbricks?schema=public"

      # NextJS Auth
      # @see: https://next-auth.js.org/configuration/options#nextauth_secret
      # You can use: `openssl rand -hex 32` to generate one
      NEXTAUTH_SECRET: "6c2525cad6c8070d210502409f79a9306a0048abfda8665f17da757da3c35a83"

      # Set this to your public-facing URL, e.g., https://example.com
      # You do not need the NEXTAUTH_URL environment variable in Vercel.
      NEXTAUTH_URL: https://survey.proximabiz.net # http://localhost:9090

      # Encryption Key is used for 2FA & Single use URLs for Link Surveys
      # You can use: $(openssl rand -hex 32) to generate one
      ENCRYPTION_KEY: "5a4a135e960e586f199ce7c2bebf715feab60a8b3d65da992497af412770da00"

      # PostgreSQL password
      POSTGRES_PASSWORD: postgres

      # Enterprise License Key
      # Required to access Enterprise-only features
      # ENTERPRISE_LICENSE_KEY:

      # Email Configuration
      MAIL_FROM: "no-repy@survey.proximabiz.net"
      SMTP_HOST: "smtp.gmail.com"
      SMTP_PORT: 587
      SMTP_SECURE_ENABLED: 0
      SMTP_USER: "jeetp@proximabiz.com"
      SMTP_PASSWORD: "mlmprjxrcrlrzeii"

      # Set the below value if you have and want to use a custom URL for the links created by the Link Shortener
      # SHORT_URL_BASE:

      # Set the below to 0 to enable Email Verification for new signups (will required Email Configuration)
      EMAIL_VERIFICATION_DISABLED: 0

      # Set the below to 0 to enable Password Reset (will required Email Configuration)
      PASSWORD_RESET_DISABLED: 1

      # Uncomment the below and set it to 1 to disable Signups
      # SIGNUP_DISABLED:

      # Uncomment the below and set it to 1 to disable Invites
      # INVITE_DISABLED:

      # Uncomment the below and set a value to have your own Privacy Page URL on the signup & login page
      # PRIVACY_URL:  

      # Uncomment the below and set a value to have your own Terms Page URL on the auth and the surveys page
      # TERMS_URL:

      # Uncomment the below and set a value to have your own Imprint Page URL on the auth and the surveys page
      # IMPRINT_URL:

      # Uncomment the below and set to 1 if you want to enable GitHub OAuth
      # GITHUB_AUTH_ENABLED:
      # GITHUB_ID:
      # GITHUB_SECRET:

      # Uncomment the below and set to 1 if you want to enable Google OAuth
      GOOGLE_AUTH_ENABLED: 1
      GOOGLE_CLIENT_ID: 506469193052-47jdq81plbtmr7ik6jpfh6n82v2fomuk.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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

      # Uncomment the below to automatically assign new users to a specific team and role within that team
      # Insert an existing team id or generate a valid CUID for a new one at https://www.getuniqueid.com/cuid (e.g. cjld2cjxh0000qzrmn831i7rn)
      # (Role Management is an Enterprise feature)
      # DEFAULT_TEAM_ID:
      # DEFAULT_TEAM_ROLE: admin

      # Uncomment and set to 1 to skip onboarding for new users
      ONBOARDING_DISABLED: 1

volumes:
  # postgres:
  #   driver: local
  uploads:
